---
- name: Update/Upgrade packages
  apt:
    upgrade: dist
    update_cache: yes

- name: Install Node.js, npm
  apt:
    name: ["nodejs", "npm"]
    state: present
    update_cache: yes

- name: Install pm2
  npm:
    name: pm2
    global: yes