---
- name: Update/Upgrade packages
  apt:
    upgrade: dist

- name: Install Node.js, npm
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - nodejs
    - npm

- name: Install pm2
  npm:
    name: pm2
    global: yes

- name: Extract artifact
  unarchive:
    src: artifact.tar.gz
    dest: /opt/app
    remote_src: yes
        
- name: Start application
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start