---
# - name: Update/Upgrade packages
#   become: yes
#   apt:
#     upgrade: yes
#     update_cache: yes

# - name: Install Node.js, npm
#   become: yes
#   apt:
#     name: ['nodejs', 'npm']
#     state: latest
#     update_cache: yes

# - name: Install pm2
#   become: yes
#   npm:
#     name: pm2
#     global: yes

- name: Extract artifact
  unarchive:
    src: artifact.tar.gz
    dest: /opt/app
    remote_src: yes
        
- name: Start application
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start