---
# - name: Update/Upgrade packages
#   become: yes
#   apt:
#     upgrade: yes
#     update_cache: yes

# - name: Install Node.js, npm
#   become: yes
#   apt:
#     name: ['nodejs', 'npm']
#     state: latest
#     update_cache: yes

# - name: Install pm2
#   become: yes
#   npm:
#     name: pm2
#     global: yes

- name: extract artifact
  become: yes
  unarchive:
    src: files/artifact.tar.gz
    dest: .

- name: Start application
  become: yes
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start
